$mod=SUPER
decoration {
  active_opacity=0.900000
  inactive_opacity=0.700000
  rounding=3
  blur:enabled = false
  shadow:enabled = false
}
misc:vfr = true

dwindle {
  pseudotile=0
  preserve_split=true
}

general {
  gaps_in=1
  gaps_out=4
  resize_on_border=true
}
gesture = 3, horizontal, workspace
gesture = 3, down, mod: SUPER, close
gesture = 3, up, mod: SUPER, scale: 1.5, fullscreen

misc {
  disable_hyprland_logo=true
}
bind=SUPER_SHIFT, Q, killactive
bind=$mod, Return, exec, alacritty
bind=$mod, t, exec, pcmanfm
bind=$mod, D, exec, $menu
bind=$mod, V, togglefloating
bind=$mod, F, fullscreen, 0
bind=$mod, h, movefocus, l
bind=$mod, j, movefocus, d
bind=$mod, k, movefocus, u
bind=$mod, l, movefocus, l
bind=$mod, e, togglesplit
bind=SUPER_SHIFT, h, movewindow, l
bind=SUPER_SHIFT, j, movewindow, d
bind=SUPER_SHIFT, k, movewindow, u
bind=SUPER_SHIFT, l, movewindow, r
bind=$mod, 1, workspace, 1
bind=$mod, 2, workspace, 2
bind=$mod, 3, workspace, 3
bind=$mod, 4, workspace, 4
bind=$mod, 5, workspace, 5
bind=$mod, 6, workspace, 6
bind=$mod, 7, workspace, 7
bind=$mod, 8, workspace, 8
bind=$mod, 9, workspace, 9
bind=$mod, 0, workspace, 10
bind=SUPER_SHIFT, 1, movetoworkspacesilent,1
bind=SUPER_SHIFT, 2, movetoworkspacesilent,2
bind=SUPER_SHIFT, 3, movetoworkspacesilent,3
bind=SUPER_SHIFT, 4, movetoworkspacesilent,4
bind=SUPER_SHIFT, 5, movetoworkspacesilent,5
bind=SUPER_SHIFT, 6, movetoworkspacesilent,6
bind=SUPER_SHIFT, 7, movetoworkspacesilent,7
bind=SUPER_SHIFT, 8, movetoworkspacesilent,8
bind=SUPER_SHIFT, 9, movetoworkspacesilent,9
bind=SUPER_SHIFT, 0, movetoworkspacesilent,10
bind=SUPER_SHIFT, c, exec, $lock
bind=SUPER_SHIFT, s, exec, $lock & systemctl suspend
bind=SUPER_SHIFT, p,exec, shutdown now
bind=$mod, s, togglegroup
bind=$mod, n, changegroupactive, f
bind=$mod, p, changegroupactive, b
binde=,XF86MonBrightnessUp, exec, brightnessctl s 5%+
binde=,XF86MonBrightnessDown, exec, brightnessctl s 5%-
binde=,XF86AudioRaiseVolume,exec,pamixer -i 5
binde=,XF86AudioLowerVolume,exec,pamixer -d 5
binde=,XF86AudioMute,exec,pamixer -t
binde=,XF86AudioMicMute,exec,pamixer --source 0 -t
binde=,XF86Bluetooth, exec, $bluetoothToggle 
bindm=$mod, mouse:272, movewindow
bindm=$mod, mouse:273, resizewindow
bindm=$SUPER_SHIFT, mouse:272, resizewindow
bind=ALTCTRL, h, movecurrentworkspacetomonitor, l
bind=ALTCTRL, l, movecurrentworkspacetomonitor, r
# trigger when the switch is turning on
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
# trigger when the switch is turning off
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1,1920x1080,-1920x0,1"
monitor=eDP-1,1920x1080@60,0x0,1
# Assign applications to right workspace
windowrule=workspace 6,match:class com.rtosta.zapzap
windowrule=workspace 3,match:class thunderbird
windowrule=workspace 2,match:class firefox
windowrule=workspace 4,match:class org.kde.okular
# Make firefox non transparant
windowrule=opacity 1 override 1 override,match:class firefox
windowrule=opacity 1 override 1 override,match:class discord
windowrule=opacity 1 override 1 override,match:class org.kde.okular
windowrule=opacity 1 override 1 override,match:class Darktable
# Make firefox PIP player work.
windowrule = float on,match:class firefox, match:title Picture-in-Picture
# windowrule = noinitialfocus, class:(firefox), title:(Picture-in-Picture)
windowrule = size 30% 30%,match:class firefox, match:title Picture-in-Picture
windowrule = move 69% 69%,match:class firefox, match:title Picture-in-Picture
